name: Pushing Hours Restriction

on:
  schedule:
    # NOTE: Execute every hour from Monday to Thursday with UTC
    - cron: '0 * * * *'

jobs:
  pushing_hours_restriction:
    runs-on: ubuntu-latest
    steps:
      - uses: hamuyuuki/pushing-hours-restriction@v0.8.1
        with:
          app_id: ${{ secrets.PUSHING_HOURS_RESTRICTION_APP_ID }}
          private_key: ${{ secrets.PUSHING_HOURS_RESTRICTION_PRIVATE_KEY }}
          start_hour: 9
          end_hour: 18
If you want reduce the number of executing actions, you can put this code.

name: Pushing Hours Restriction

on:
  schedule:
    # NOTE: Execute start_hour and end_hour from Monday to Friday with UTC
    - cron: '0 9,19 * * MON-FRI'

jobs:
  pushing_hours_restriction:
    runs-on: ubuntu-latest
    steps:
      - uses: hamuyuuki/pushing-hours-restriction@v0.8.1
        with:
          app_id: ${{ secrets.PUSHING_HOURS_RESTRICTION_APP_ID }}
          private_key: ${{ secrets.PUSHING_HOURS_RESTRICTION_PRIVATE_KEY }}
          start_hour: 9
          end_hour: 19
